# One CPU inference path on every supported platform. No system voice or cloud fallback.
set(ortho_ort_version 1.23.2)
if(APPLE)
    if(CMAKE_OSX_ARCHITECTURES MATCHES "x86_64" OR CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
        set(ortho_ort_platform osx-x86_64)
        set(ortho_ort_hash d10359e16347b57d9959f7e80a225a5b4a66ed7d7e007274a15cae86836485a6)
    else()
        set(ortho_ort_platform osx-arm64)
        set(ortho_ort_hash b4d513ab2b26f088c66891dbbc1408166708773d7cc4163de7bdca0e9bbb7856)
    endif()
elseif(WIN32)
    set(ortho_ort_platform win-x64)
    set(ortho_ort_hash 0b38df9af21834e41e73d602d90db5cb06dbd1ca618948b8f1d66d607ac9f3cd)
else()
    set(ortho_ort_platform linux-x64)
    set(ortho_ort_hash 1fa4dcaef22f6f7d5cd81b28c2800414350c10116f5fdd46a2160082551c5f9b)
endif()
if(WIN32)
    set(ortho_ort_extension zip)
else()
    set(ortho_ort_extension tgz)
endif()
FetchContent_Declare(ortho_ort
    URL "https://github.com/microsoft/onnxruntime/releases/download/v${ortho_ort_version}/onnxruntime-${ortho_ort_platform}-${ortho_ort_version}.${ortho_ort_extension}"
    URL_HASH "SHA256=${ortho_ort_hash}" DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
FetchContent_Declare(ortho_chatterbox
    URL https://codeload.github.com/birdup000/chatterboxcpp/tar.gz/1a9a4fc00a6caa8c8bb9bee533225f40661e4220
    URL_HASH SHA256=c9f0f6d377910110dcbf52ade5eae7645623af6358cefd70cdf6329a9f339e6a DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
FetchContent_Declare(ortho_unicode
    URL https://codeload.github.com/JuliaStrings/utf8proc/tar.gz/refs/tags/v2.10.0
    URL_HASH SHA256=6f4f1b639daa6dca9f80bc5db1233e9cbaa31a67790887106160b33ef743f136 DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
FetchContent_Declare(ortho_audio
    URL https://raw.githubusercontent.com/mackron/miniaudio/0.11.22/miniaudio.h
    URL_HASH SHA256=9019743287e443c55e5737a7297f38e5e358561701d6db2d905afb114390c410 DOWNLOAD_NO_EXTRACT TRUE)
# Use audited runtime modules only; upstream downloaders, servers, and native checkpoint code stay out.
foreach(dependency ortho_ort ortho_chatterbox ortho_unicode ortho_audio)
    FetchContent_GetProperties(${dependency})
    if(NOT ${dependency}_POPULATED)
        FetchContent_Populate(${dependency})
    endif()
endforeach()
add_library(ortho-unicode STATIC "${ortho_unicode_SOURCE_DIR}/utf8proc.c" src/speech/portable_unicode.cpp)
target_include_directories(ortho-unicode PUBLIC src "${ortho_unicode_SOURCE_DIR}")
target_compile_definitions(ortho-unicode PUBLIC UTF8PROC_STATIC)

set(ortho_speech_source "${CMAKE_BINARY_DIR}/speech-source")
file(MAKE_DIRECTORY "${ortho_speech_source}/include")
file(COPY "${ortho_chatterbox_SOURCE_DIR}/include/chatterbox" DESTINATION "${ortho_speech_source}/include")
file(READ "${ortho_speech_source}/include/chatterbox/types.hpp" text)
string(REPLACE "#include <cstdint>" "#include <cstdint>\n#include <functional>" text "${text}")
string(REPLACE "uint64_t seed = 0;" "uint64_t seed = 0;\n  std::function<bool()> cancelled;" text "${text}")
file(WRITE "${ortho_speech_source}/include/chatterbox/types.hpp" "${text}")
set(ortho_chatterbox_sources)
foreach(module audio backend json manifest sampler text tokenizer onnx_backend)
    file(READ "${ortho_chatterbox_SOURCE_DIR}/src/${module}.cpp" text)
    if(module STREQUAL "audio" OR module STREQUAL "json")
        string(PREPEND text "#include <filesystem>\n")
        string(REPLACE "in(path, std::ios::binary)" "in(std::filesystem::u8path(path), std::ios::binary)" text "${text}")
        string(REPLACE "out(path, std::ios::binary)" "out(std::filesystem::u8path(path), std::ios::binary)" text "${text}")
    elseif(module STREQUAL "text")
        string(PREPEND text "#include \"speech/portable_unicode.hpp\"\n")
        string(REPLACE "return to_lower_ascii(text);" "return ortho::speech_unicode(text);" text "${text}")
        string(REPLACE "c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));" "if(c>='A' && c<='Z') c=static_cast<char>(c+('a'-'A'));" text "${text}")
    elseif(module STREQUAL "tokenizer")
        string(PREPEND text "namespace { bool ortho_ascii_space(unsigned char c) {return c==' '||c=='\\t'||c=='\\n'||c=='\\r'||c=='\\v'||c=='\\f';} bool ortho_ascii_word(unsigned char c) {return (c>='a'&&c<='z')||(c>='A'&&c<='Z')||(c>='0'&&c<='9');} }\n")
        string(REPLACE "std::isspace" "ortho_ascii_space" text "${text}")
        string(REPLACE "std::isalnum" "ortho_ascii_word" text "${text}")
    elseif(module STREQUAL "onnx_backend")
        string(REPLACE "#include \"chatterbox/model_config.hpp\"" "" text "${text}")
        string(REPLACE "SetIntraOpNumThreads(0)" "SetIntraOpNumThreads(4)" text "${text}")
        string(REPLACE "SetInterOpNumThreads(0)" "SetInterOpNumThreads(1)" text "${text}")
        string(FIND "${text}" "    // CUDA EP" cuda_begin)
        string(FIND "${text}" "    const auto root" cuda_end)
        string(SUBSTRING "${text}" 0 ${cuda_begin} prefix)
        string(SUBSTRING "${text}" ${cuda_end} -1 suffix)
        set(text "${prefix}    env_.DisableTelemetryEvents();\n${suffix}")
        string(REPLACE ".string().c_str(), session_options_" ".native().c_str(), session_options_" text "${text}")
        string(REPLACE "return create_native_backend(manifest);" "throw Error(\"Only the pinned ONNX backend is supported\");" text "${text}")
        string(REPLACE "while (static_cast<int64_t>(all_ids.size()) < max_length) {" "while (static_cast<int64_t>(all_ids.size()) < max_length) {\n      if(options.cancelled && options.cancelled()) throw Error(\"Speech cancelled\");" text "${text}")
        string(REPLACE "if (emitted_stop_token && !generated.empty()) {" "if(!emitted_stop_token) throw Error(\"Speech token limit reached; truncated audio rejected\");\n    if(options.cancelled && options.cancelled()) throw Error(\"Speech cancelled\");\n    if (emitted_stop_token && !generated.empty()) {" text "${text}")
        # These two upstream position helpers need no native checkpoint implementation.
        string(REPLACE "namespace {" [=[namespace {
std::vector<int64_t> t3_prompt_position_ids(const std::vector<int64_t>& ids) {
  std::vector<int64_t> result; int64_t position=0;
  for(auto id:ids) result.push_back(id>=kStartSpeechToken?0:position++);
  return result;
}
int64_t t3_next_speech_position_id(const std::vector<int64_t>& ids) {
  if(ids.empty()) throw Error("Empty speech token sequence");
  for(size_t i=ids.size();i>0;--i) if(ids[i-1]==kStartSpeechToken) return ids.size()-i;
  return ids.size()-1;
}
]=] text "${text}")
    endif()
    file(WRITE "${ortho_speech_source}/${module}.cpp" "${text}")
    list(APPEND ortho_chatterbox_sources "${ortho_speech_source}/${module}.cpp")
endforeach()
add_library(ortho-chatterbox STATIC ${ortho_chatterbox_sources})
target_compile_definitions(ortho-chatterbox PRIVATE CHATTERBOXCPP_WITH_ONNXRUNTIME=1)
target_include_directories(ortho-chatterbox PUBLIC "${ortho_speech_source}/include" PRIVATE "${ortho_ort_SOURCE_DIR}/include")
target_link_libraries(ortho-chatterbox PRIVATE ortho-unicode)
if(APPLE)
    set(ortho_ort_library "${ortho_ort_SOURCE_DIR}/lib/libonnxruntime.${ortho_ort_version}.dylib")
elseif(WIN32)
    # ONNX exposes a C ABI. MinGW can use the official COFF import library.
    set(ortho_ort_library "${ortho_ort_SOURCE_DIR}/lib/onnxruntime.lib")
else()
    set(ortho_ort_library "${ortho_ort_SOURCE_DIR}/lib/libonnxruntime.so.${ortho_ort_version}")
endif()
target_link_libraries(ortho-chatterbox PUBLIC "${ortho_ort_library}")
add_library(ortho-speech STATIC src/speech/portable_speech.cpp src/speech/pcm_output.cpp)
file(READ "${CMAKE_SOURCE_DIR}/tools/speech/voice-pack.json" ortho_pack_manifest)
string(JSON ortho_pack_id GET "${ortho_pack_manifest}" id)
string(JSON ortho_pack_count LENGTH "${ortho_pack_manifest}" files)
math(EXPR ortho_pack_last "${ortho_pack_count}-1")
set(ortho_pack_header "#pragma once\n#include <array>\n#include <cstdint>\n#include <utility>\nnamespace ortho {\ninline constexpr char voice_pack_id[]=\"${ortho_pack_id}\";\ninline constexpr std::array<std::pair<const char*,uint64_t>,${ortho_pack_count}> voice_pack_files={{\n")
foreach(index RANGE 0 ${ortho_pack_last})
    string(JSON name MEMBER "${ortho_pack_manifest}" files ${index})
    string(JSON size GET "${ortho_pack_manifest}" files "${name}" size)
    string(APPEND ortho_pack_header "{\"${name}\",${size}},\n")
endforeach()
string(APPEND ortho_pack_header "}};\n}\n")
file(WRITE "${ortho_speech_source}/include/speech_voice_manifest.hpp" "${ortho_pack_header}")
target_include_directories(ortho-speech PRIVATE "${ortho_audio_SOURCE_DIR}")
target_link_libraries(ortho-speech PUBLIC ortho-core PRIVATE ortho-chatterbox ${CMAKE_DL_LIBS})
file(MAKE_DIRECTORY "${ortho_speech_source}/licenses")
configure_file("${ortho_chatterbox_SOURCE_DIR}/LICENSE" "${ortho_speech_source}/licenses/Chatterbox-MIT.txt" COPYONLY)
configure_file("${ortho_ort_SOURCE_DIR}/LICENSE" "${ortho_speech_source}/licenses/ONNX-Runtime-MIT.txt" COPYONLY)
configure_file("${ortho_ort_SOURCE_DIR}/ThirdPartyNotices.txt" "${ortho_speech_source}/licenses/ONNX-Runtime-dependencies.txt" COPYONLY)
configure_file("${ortho_unicode_SOURCE_DIR}/LICENSE.md" "${ortho_speech_source}/licenses/utf8proc-MIT-Unicode.txt" COPYONLY)
file(READ "${ortho_audio_SOURCE_DIR}/miniaudio.h" ortho_audio_header)
string(FIND "${ortho_audio_header}" "This software is available as a choice" ortho_audio_license_begin REVERSE)
string(SUBSTRING "${ortho_audio_header}" ${ortho_audio_license_begin} -1 ortho_audio_license)
file(WRITE "${ortho_speech_source}/licenses/miniaudio-public-domain.txt" "${ortho_audio_license}")
if(APPLE)
    target_link_libraries(ortho-speech PRIVATE "-framework CoreAudio" "-framework AudioToolbox" "-framework CoreFoundation")
elseif(WIN32)
    target_link_libraries(ortho-speech PRIVATE ole32)
endif()
