# One CPU inference path on every supported platform. No system voice or cloud fallback.
set(ortho_ort_version 1.23.2)
if(APPLE)
    if(CMAKE_OSX_ARCHITECTURES MATCHES "x86_64" OR CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
        set(ortho_ort_platform osx-x86_64)
        set(ortho_ort_hash d10359e16347b57d9959f7e80a225a5b4a66ed7d7e007274a15cae86836485a6)
    else()
        set(ortho_ort_platform osx-arm64)
        set(ortho_ort_hash b4d513ab2b26f088c66891dbbc1408166708773d7cc4163de7bdca0e9bbb7856)
    endif()
elseif(WIN32)
    set(ortho_ort_platform win-x64)
    set(ortho_ort_hash 0b38df9af21834e41e73d602d90db5cb06dbd1ca618948b8f1d66d607ac9f3cd)
else()
    set(ortho_ort_platform linux-x64)
    set(ortho_ort_hash 1fa4dcaef22f6f7d5cd81b28c2800414350c10116f5fdd46a2160082551c5f9b)
endif()
if(WIN32)
    set(ortho_ort_extension zip)
else()
    set(ortho_ort_extension tgz)
endif()
FetchContent_Declare(ortho_ort
    URL "https://github.com/microsoft/onnxruntime/releases/download/v${ortho_ort_version}/onnxruntime-${ortho_ort_platform}-${ortho_ort_version}.${ortho_ort_extension}"
    URL_HASH "SHA256=${ortho_ort_hash}" DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
FetchContent_Declare(ortho_sonic
    URL https://codeload.github.com/waywardgeek/sonic/tar.gz/b93885dcb70aae50c6f76b0fe4e0868f029a077e
    URL_HASH SHA256=b76d832649306b53e716c271014c0b8f89f6bcefc43e5068a2eca3cf1946324c DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
FetchContent_Declare(ortho_audio
    URL https://raw.githubusercontent.com/mackron/miniaudio/0.11.22/miniaudio.h
    URL_HASH SHA256=9019743287e443c55e5737a7297f38e5e358561701d6db2d905afb114390c410 DOWNLOAD_NO_EXTRACT TRUE)
# Use audited runtime modules only; upstream downloaders, servers, and native checkpoint code stay out.
# None of these archives has a CMakeLists.txt, so this only downloads and unpacks them.
FetchContent_MakeAvailable(ortho_ort ortho_audio ortho_sonic)
set(ortho_speech_source "${CMAKE_BINARY_DIR}/speech-source")
if(APPLE)
    set(ortho_ort_library "${ortho_ort_SOURCE_DIR}/lib/libonnxruntime.${ortho_ort_version}.dylib")
elseif(WIN32)
    # ONNX exposes a C ABI. MinGW can use the official COFF import library.
    set(ortho_ort_library "${ortho_ort_SOURCE_DIR}/lib/onnxruntime.lib")
else()
    set(ortho_ort_library "${ortho_ort_SOURCE_DIR}/lib/libonnxruntime.so.${ortho_ort_version}")
endif()
add_library(ortho-kokoro STATIC src/speech/kokoro_audio.cpp src/speech/kokoro_text.cpp)
target_include_directories(ortho-kokoro PUBLIC src PRIVATE "${ortho_ort_SOURCE_DIR}/include")
target_link_libraries(ortho-kokoro PRIVATE "${ortho_ort_library}")
if(MINGW)
    # The ONNX Runtime headers use _stdcall, which GCC defines only outside strict ISO mode.
    target_compile_definitions(ortho-kokoro PRIVATE _stdcall=__stdcall)
endif()
add_executable(ortho-kokoro-audio-probe tools/speech/kokoro_audio_probe.cpp)
target_link_libraries(ortho-kokoro-audio-probe PRIVATE ortho-kokoro)
add_executable(ortho-kokoro-text-probe tools/speech/kokoro_text_probe.cpp)
target_link_libraries(ortho-kokoro-text-probe PRIVATE ortho-kokoro)
add_library(ortho-speech STATIC src/speech/portable_speech.cpp src/speech/pcm_output.cpp src/speech/tempo.cpp "${ortho_sonic_SOURCE_DIR}/sonic.c")
target_include_directories(ortho-speech PRIVATE "${ortho_audio_SOURCE_DIR}" "${ortho_sonic_SOURCE_DIR}")
target_link_libraries(ortho-speech PUBLIC ortho-core PRIVATE ortho-kokoro ${CMAKE_DL_LIBS})
if(BUILD_TESTING)
    add_executable(ortho-portable-speech-tests tests/portable_speech_test.cpp src/speech/portable_speech.cpp)
    target_link_libraries(ortho-portable-speech-tests PRIVATE ortho-core ortho-kokoro Threads::Threads)
    add_test(NAME portable-speech-streaming COMMAND ortho-portable-speech-tests "${CMAKE_BINARY_DIR}/test-stream-speech")
    add_executable(ortho-tempo-tests tests/tempo_test.cpp src/speech/tempo.cpp "${ortho_sonic_SOURCE_DIR}/sonic.c")
    target_include_directories(ortho-tempo-tests PRIVATE src "${ortho_sonic_SOURCE_DIR}")
    add_test(NAME speech-tempo COMMAND ortho-tempo-tests)
endif()
file(MAKE_DIRECTORY "${ortho_speech_source}/licenses")
configure_file("${ortho_ort_SOURCE_DIR}/LICENSE" "${ortho_speech_source}/licenses/ONNX-Runtime-MIT.txt" COPYONLY)
configure_file("${ortho_ort_SOURCE_DIR}/ThirdPartyNotices.txt" "${ortho_speech_source}/licenses/ONNX-Runtime-dependencies.txt" COPYONLY)
configure_file("${ortho_sonic_SOURCE_DIR}/LICENSE" "${ortho_speech_source}/licenses/Sonic-Apache-2.0.txt" COPYONLY)
file(READ "${ortho_audio_SOURCE_DIR}/miniaudio.h" ortho_audio_header)
string(FIND "${ortho_audio_header}" "This software is available as a choice" ortho_audio_license_begin REVERSE)
string(SUBSTRING "${ortho_audio_header}" ${ortho_audio_license_begin} -1 ortho_audio_license)
file(WRITE "${ortho_speech_source}/licenses/miniaudio-public-domain.txt" "${ortho_audio_license}")
if(APPLE)
    target_link_libraries(ortho-speech PRIVATE "-framework CoreAudio" "-framework AudioToolbox" "-framework CoreFoundation")
elseif(WIN32)
    target_link_libraries(ortho-speech PRIVATE ole32)
endif()
